services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shms'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5435:5432'
    volumes:
      - ../../.database/sql:/docker-entrypoint-initdb.d

